org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_base_version=1.21
minecraft_version_range=[1.21,)
neo_version=21.1.180
neo_version_range=[21,)
loader_version_range=[1,)

#mapping_channel=parchment
parchment_mc_version=1.21.1
parchment_mapping_version=2024.11.17

mod_id=theaurorian
mod_name=The Aurorian
mod_license=MIT
mod_version=1.19.2-2.7-playtest
mod_group_id=shiroroku.theaurorian
mod_link=https://github.com/shiroroku/TheAurorian
mod_authors=shiroroku(elise), LShiftLess, Music - Reexy: https://www.youtube.com/channel/UCgM9XlNy-qCOWiIGlcaeDKg https://www.fiverr.com/reexymusic
mod_description=Explore a land beyond this world, bathed in moonlight and shrouded in nature.

#https://maven.theillusivec4.top/top/theillusivec4/curios/curios-forge/
curios_version=9.5.1+1.21.1
jei_version=19.21.2.313
geckolib_version=4.7.6
appleskin_version=3.0.7